"""updated action tables

Revision ID: 1cc74b0b66a6
Revises: af79fd9d5f90
Create Date: 2022-07-19 12:33:51.415661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cc74b0b66a6"
down_revision = "af79fd9d5f90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_delete_actions",
        sa.Column("trigger_id", sa.BigInteger(), nullable=False),
    )
    op.create_foreign_key(
        None, "message_delete_actions", "triggers", ["trigger_id"], ["id"]
    )
    op.add_column(
        "message_send_actions",
        sa.Column("message_content", sa.String(), nullable=False),
    )
    op.add_column(
        "message_send_actions",
        sa.Column("trigger_id", sa.BigInteger(), nullable=False),
    )
    op.create_foreign_key(
        None, "message_send_actions", "triggers", ["trigger_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message_send_actions", type_="foreignkey")  # type: ignore
    op.drop_column("message_send_actions", "trigger_id")
    op.drop_column("message_send_actions", "message_content")
    op.drop_constraint(None, "message_delete_actions", type_="foreignkey")  # type: ignore
    op.drop_column("message_delete_actions", "trigger_id")
    # ### end Alembic commands ###
