"""triggers table

Revision ID: 31fe6e939683
Revises:
Create Date: 2022-07-12 21:26:21.646193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31fe6e939683"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "triggers",
        sa.Column("id", sa.BigInteger(), nullable=False, auto_increment=True),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("Message", "Reaction", name="triggertype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("triggers")
    # ### end Alembic commands ###
