"""triggers table

Revision ID: 36b472f93b45
Revises:
Create Date: 2022-07-13 08:09:50.515179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36b472f93b45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "triggers",
        sa.Column("id", sa.BigInteger(), nullable=False, auto_increment=True),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "Message",
                "ReactionAdd",
                "ReactionRemove",
                "MemberJoin",
                "MemberLeave",
                name="triggertype",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("triggers")
    # ### end Alembic commands ###
