"""added activation_params column to triggers

Revision ID: 60c4ba99cb9c
Revises: 1cc74b0b66a6
Create Date: 2022-07-20 16:32:02.501016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60c4ba99cb9c"
down_revision = "1cc74b0b66a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "triggers", sa.Column("activation_params", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("triggers", "activation_params")
    # ### end Alembic commands ###
