"""on delete cascade for triggers

Revision ID: a657577ca971
Revises: 60c4ba99cb9c
Create Date: 2022-07-20 16:59:08.149661

"""
from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a657577ca971"
down_revision = "60c4ba99cb9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "message_delete_actions_trigger_id_fkey",
        "message_delete_actions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "message_delete_actions",
        "triggers",
        ["trigger_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "message_send_actions_trigger_id_fkey",
        "message_send_actions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "message_send_actions",
        "triggers",
        ["trigger_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message_send_actions", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "message_send_actions_trigger_id_fkey",
        "message_send_actions",
        "triggers",
        ["trigger_id"],
        ["id"],
    )
    op.drop_constraint(None, "message_delete_actions", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "message_delete_actions_trigger_id_fkey",
        "message_delete_actions",
        "triggers",
        ["trigger_id"],
        ["id"],
    )
    # ### end Alembic commands ###
