"""generalised action table

Revision ID: fc174d28712a
Revises: a657577ca971
Create Date: 2022-07-21 15:02:58.189417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc174d28712a"
down_revision = "a657577ca971"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("id", sa.BigInteger(), nullable=False, auto_increment=True),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "MessageSend",
                "MessageDelete",
                "ReactionAdd",
                "ReactionRemove",
                name="actiontype",
            ),
            nullable=False,
        ),
        sa.Column("action_params", sa.JSON(), nullable=False),
        sa.Column("trigger_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trigger_id"], ["triggers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("message_send_actions")
    op.drop_table("message_delete_actions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_delete_actions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "guild_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "channel_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "message_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "trigger_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["triggers.id"],
            name="message_delete_actions_trigger_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="message_delete_actions_pkey"),
    )
    op.create_table(
        "message_send_actions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "guild_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "channel_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "message_content",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "trigger_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["triggers.id"],
            name="message_send_actions_trigger_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="message_send_actions_pkey"),
    )
    op.drop_table("actions")
    # ### end Alembic commands ###
